Repository salesforce/ml4ir, pull requests merged in 2020-03, with the labels that each got.

#9 Computing groupwise metrics
  python/ml4ir/config/features.py
  python/ml4ir/config/parse_args.py
  python/ml4ir/model/metrics/metrics_helper.py
  python/ml4ir/model/pipeline.py
  python/ml4ir/model/ranking_model.py
  python/ml4ir/tests/data/csv/feature_config.yaml
  python/ml4ir/tests/data/csv/test/file_0.csv
  python/ml4ir/tests/data/csv/train/file_0.csv
  python/ml4ir/tests/data/csv/validation/file_0.csv
  python/ml4ir/tests/data/tfrecord/feature_config.yaml
  python/ml4ir/tests/data/tfrecord/test/file_0.tfrecord
  python/ml4ir/tests/data/tfrecord/train/file_0.tfrecord
  python/ml4ir/tests/data/tfrecord/validation/file_0.tfrecord
  python/ml4ir/tests/test_losses.py
  python/ml4ir/tests/test_metrics.py
  python/ml4ir/tests/test_ranking_model.py
Labels: cla:signed

#14 Adding code to parse model config yaml file to extract feature metadata
  jvm/ml4ir-inference/pom.xml
  jvm/ml4ir-inference/src/main/java/ml4ir/inference/tensorflow/ModelFeaturesParser.java
  jvm/ml4ir-inference/src/main/java/ml4ir/inference/tensorflow/utils/ModelFeatures.java
  jvm/ml4ir-inference/src/test/java/ml4ir/inference/tensorflow/ModelFeaturesParserTest.java
  jvm/ml4ir-inference/src/test/resources/model_features.yaml
Labels: enhancement

#12 Character embeddings + Cleaning up context feature tiling
  python/ml4ir/config/default_model_config.yaml
  python/ml4ir/config/keys.py
  python/ml4ir/config/parse_args.py
  python/ml4ir/data/csv_reader.py
  python/ml4ir/data/ranking_dataset.py
  python/ml4ir/data/tfrecord_reader.py
  python/ml4ir/data/tfrecord_writer.py
  python/ml4ir/features/feature_config.py
  python/ml4ir/features/feature_layer.py
  python/ml4ir/features/preprocessing.py
  python/ml4ir/model/optimizer.py
  python/ml4ir/model/pipeline.py
  python/ml4ir/model/ranking_model.py
  python/ml4ir/tests/data/csv/feature_config.yaml
  python/ml4ir/tests/data/tfrecord/feature_config.yaml
  python/ml4ir/tests/test_features.py
  python/ml4ir/tests/test_losses.py
  python/ml4ir/tests/test_metrics.py
  python/ml4ir/tests/test_ranking_dataset.py
  python/ml4ir/tests/test_ranking_model.py
  python/ml4ir/tests/test_serving.py
Labels: cla:signed, enhancement
